#!/usr/bin/env bash
# Phase A — deploy OpenClaw gateway auto-defaults to Paperclip.
#
# Steps:
#   1. Read gateway token from /root/.openclaw/openclaw.json (needs sudo).
#   2. Write /etc/paperclip/openclaw-gateway.env (owned root:paperclip, mode 640)
#      with OPENCLAW_GATEWAY_URL + OPENCLAW_GATEWAY_TOKEN.
#   3. Add EnvironmentFile= line to /etc/systemd/system/paperclip.service if
#      not already present (backup first).
#   4. Apply the Python patch to server/src/routes/agents.ts.
#   5. Reload systemd + restart paperclip.
#   6. Smoke: print that EnvironmentFile was loaded and the helper is present.
set -euo pipefail

echo "== 1. extract token from /root/.openclaw/openclaw.json =="
TOKEN=$(sudo python3 -c "import json,sys; d=json.load(open('/root/.openclaw/openclaw.json')); sys.stdout.write(((d.get('gateway') or {}).get('auth') or {}).get('token') or '')")
if [[ -z "$TOKEN" ]]; then
  echo "ERR: could not read gateway.auth.token from openclaw.json" >&2
  sudo python3 -c "import json; d=json.load(open('/root/.openclaw/openclaw.json')); print('top keys:', list(d.keys())); print('gateway keys:', list((d.get('gateway') or {}).keys()))" >&2
  exit 2
fi
echo "[ok] token length=${#TOKEN}"

echo "== 2. write /etc/paperclip/openclaw-gateway.env =="
sudo mkdir -p /etc/paperclip
sudo tee /etc/paperclip/openclaw-gateway.env >/dev/null <<EOF
# Auto-generated by phaseA_deploy.sh $(date -u +%FT%TZ). Paperclip reads these
# to auto-populate new openclaw_gateway agents' adapterConfig.url and
# adapterConfig.headers["x-openclaw-token"] so agents work the instant they're
# created. Token mirrors /root/.openclaw/openclaw.json \`token\`. Re-run this
# script after a token rotation.
OPENCLAW_GATEWAY_URL=ws://127.0.0.1:18789
OPENCLAW_GATEWAY_TOKEN=${TOKEN}
EOF
sudo chown root:paperclip /etc/paperclip/openclaw-gateway.env
sudo chmod 640 /etc/paperclip/openclaw-gateway.env
echo "[ok] wrote /etc/paperclip/openclaw-gateway.env (640 root:paperclip)"

echo "== 3. patch /etc/systemd/system/paperclip.service =="
UNIT=/etc/systemd/system/paperclip.service
if ! sudo grep -q 'openclaw-gateway.env' "$UNIT"; then
  sudo cp "$UNIT" "${UNIT}.bak-$(date +%s)"
  # Insert the EnvironmentFile line right before ExecStart=
  sudo python3 <<'PY'
import pathlib
p = pathlib.Path("/etc/systemd/system/paperclip.service")
txt = p.read_text()
if "openclaw-gateway.env" in txt:
    raise SystemExit(0)
lines = txt.splitlines(keepends=True)
out = []
inserted = False
for line in lines:
    if not inserted and line.startswith("ExecStart="):
        out.append("EnvironmentFile=-/etc/paperclip/openclaw-gateway.env\n")
        inserted = True
    out.append(line)
p.write_text("".join(out))
print("[systemd] EnvironmentFile added")
PY
  echo "[ok] paperclip.service patched + backed up"
else
  echo "[skip] EnvironmentFile already present in paperclip.service"
fi

echo "== 4. apply Python patch to agents.ts =="
sudo -u paperclip python3 /tmp/phaseA_patch_agents_ts.py

echo "== 5. reload systemd + restart paperclip =="
sudo systemctl daemon-reload
sudo systemctl restart paperclip
sleep 4
systemctl is-active paperclip

echo "== 6. verify env var is loaded + helper is compiled =="
systemctl show paperclip -p Environment --value | tr ' ' '\n' | grep -E '^OPENCLAW_GATEWAY' || echo "[warn] env vars not visible via Environment= (check EnvironmentFile)"
# systemctl doesn't echo EnvironmentFile vars into Environment=, read /proc/<pid>/environ instead
MAIN_PID=$(systemctl show -p MainPID paperclip --value)
if [[ -n "$MAIN_PID" && "$MAIN_PID" != "0" ]]; then
  echo "[env] main PID=$MAIN_PID"
  sudo cat /proc/$MAIN_PID/environ 2>/dev/null | tr '\0' '\n' | grep -E '^OPENCLAW_GATEWAY' || echo "[warn] no OPENCLAW_GATEWAY env visible on main process"
fi

echo "== 7. helper present in source =="
grep -c 'ensureOpenClawGatewayUrlAndToken' /home/paperclip/paperclip/server/src/routes/agents.ts

echo "== done =="
